use inc::Module::Package 'Gugod:style';

requires
    'local::lib'     => '1.0',
    'JSON'           => '2.53',
    'Exporter::Lite' => '0.02',
    'HTTP::Tiny'     => '0.012',
    'File::ShareDir' => '1.03',
    'File::Find'     => '0',
    'File::Spec'     => '0',
    'File::Temp'     => '0',
    'parent'         => '0.225',
    'CLI::Framework' => '0.05';
recommends 'B::Hooks::Parser' => '0.09';
